Reports/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Reports.DAL;


namespace Reports.Controllers
{
    public class AdminController : Controller
    {
        IConfiguration _iconfiguration;
        private readonly ReportData reportData;

        public AdminController(IConfiguration configuration)
        {
            _iconfiguration = configuration;
            reportData = new ReportData(configuration);
        }


        public IActionResult Index()
        {
            return View();
        }

        [HttpPost("Login")]
        public ActionResult Login(User user)
        {
            if (user.Username != "" && user.Password != null)
            {
                string password = Common.GenerateMD5HashCode(user.Password);
                var obj = reportData.AuthenticateUser(user.Username, password);

                if (obj != null)
                {
                    TempData["userId"] = Convert.ToInt32(obj.UserId);
                    TempData.Keep();
                    return Json("true");
                }
                else
                {
                    return Json("false");
                }
            }
            return View();
        }

        public ActionResult Logout()
        {
            TempData["userId"] = 0;
            return Json("true");
        }
    }
}

Reports/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Reports.DAL;
using OfficeOpenXml;
using OfficeOpenXml.Style;
using System.ServiceProcess;
using Microsoft.Extensions.Logging;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Reports.Controllers
{
    public class ReportsController : Controller
    {
        IConfiguration _iconfiguration;
        private readonly ReportData reportData;
        ILogger<ReportsController> _logger;

        public ReportsController(IConfiguration configuration, ILogger<ReportsController> logger)
        {
            _iconfiguration = configuration;
            reportData = new ReportData(configuration);
            _logger = logger;
        }
        public ActionResult Index()
        {
            var sessUserId = Convert.ToInt32(TempData["userId"]);
            if (sessUserId != 0)
            {
                FilterData filter = FilteredData();
                ViewBag.FromDate = filter.FromDate.ToString("dd/MM/yyy", CultureInfo.InvariantCulture);
                ViewBag.ToDate = filter.ToDate.ToString("dd/MM/yyyy", CultureInfo.InvariantCulture);

                FileStatusModel viewModel = new FileStatusModel();
                viewModel.ListFileStatus = reportData.GetFileStatus();
                TempData["userId"] = sessUserId;
                TempData.Keep();

                List<Service> serviceNames = new List<Service>();
                serviceNames = reportData.GetServiceNames();
                ViewBag.ServiceName = serviceNames;
                return View(viewModel);
            }
            else
            {
                return RedirectToAction("Index", "Admin");
            }
                
        }
        public FilterData FilteredData()
        {
            FilterData filter = new FilterData
            {
                FromDate = DateTime.Today.AddMonths(-1),
                ToDate = DateTime.Today
            };

            return filter;
        }
        #region Search Report
        public JsonResult ReportsSearchResult(FilterData data)
        {
            try
            {
                var sessUserId = Convert.ToInt32(TempData["userId"]);
                if (sessUserId != 0)
                {
                    List<Report> lstReport;
                    ReportDetails countDetails;

                    //if (data.FromDate == data.ToDate)
                    //{
                    //    data.ToDate = data.ToDate.AddDays(1);
                    //}

                    SearchDetails searchDetails = new SearchDetails
                    {
                        Category = data.Category,
                        Status = data.Status,
                        FromDate = data.FromDate,
                        ToDate = data.ToDate
                    };

                    TempData["CategoryId"] = data.Category;
                    TempData["StatusId"] = data.Status;
                    TempData["FromDate"] = Convert.ToDateTime(data.FromDate);
                    TempData["ToDate"] = Convert.ToDateTime(data.ToDate);
                    TempData["userId"] = sessUserId;
                    TempData.Keep();

                    countDetails = reportData.GetCounts(searchDetails);

                    List<Column> columns;
                    if (data.Category != (int)MainCategory.Pending_Emails)
                    {
                        columns = new List<Column>
                        {
                            new Column{Data = "userName", Name = "UserName"},
                            new Column{Data = "csvName", Name = "CsvName"},
                            new Column{Data = "createdOn", Name = "CreatedOn"},
                            new Column{Data = "updatedOn", Name = "UpdatedOn"},
                            new Column{Data = "statusName", Name = "StatusName"}
                        };
                    }
                    else
                    {
                        columns = new List<Column>
                        {
                            new Column{Data = "toEmail", Name = "ToEmail"},
                            new Column{Data = "subject", Name = "Subject"},
                            new Column{Data = "createdOn", Name = "CreatedOn"},
                            new Column{Data = "updatedOn", Name = "UpdatedOn"},
                            new Column{Data = "emailType", Name = "EmailType"}
                        };
                    }

                    lstReport = reportData.GetReportData(searchDetails);
                    var Jdata = new
                    {
                        data = lstReport,
                        columns,
                        countDetails
                    };
                    return Json(new { success = "true", Jdata });
                }
                else
                {
                    return Json(false);
                }
            }
            catch(Exception ex)
            {
                _logger.LogInformation(ex.Message + ex.StackTrace);
                return null;
            }
        } 
        #endregion
        #region Download Excel
        public ActionResult Excel()
        {
            try
            {
                var categoryId = Convert.ToInt32(TempData["CategoryId"]);

                SearchDetails searchDetails = new SearchDetails
                {
                    Category = categoryId,
                    Status = Convert.ToInt32(TempData["StatusId"]),
                    FromDate = Convert.ToDateTime(TempData["FromDate"]),
                    ToDate = Convert.ToDateTime(TempData["ToDate"])
                };

                string[] columnHeaders;

                if (categoryId == (int)MainCategory.Pending_Emails)
                {
                    columnHeaders = new string[]
                    {
                    "Email To",
                    "Subject",
                    "Email Type",
                    "Created On",
                    "Updated On"
                    };
                } else
                {
                    columnHeaders = new string[]
                    {
                    "User Name",
                    "CSV Name",
                    "Created On",
                    "Status",
                    "Updated On"
                    };

                }
                byte[] result;

                using (var package = new ExcelPackage())
                {
                    // add a new worksheet to the empty workbook
                    var worksheet = package.Workbook.Worksheets.Add("Current Employee"); //Worksheet name
                    using (var cells = worksheet.Cells[1, 1, 1, 5])
                    {
                        cells.Style.Font.Bold = true;
                    }
                    //First add the headers
                    for (var i = 0; i < columnHeaders.Count(); i++)
                    {
                        worksheet.Cells[1, i + 1].Value = columnHeaders[i];
                    }
                    //Add values
                    var j = 2;
                    foreach (var employee in reportData.GetReportData(searchDetails))
                    {
                        if (categoryId > (int)MainCategory.Pending_Emails)
                        {
                            worksheet.Cells["A" + j].Value = employee.UserName;
                            worksheet.Cells["B" + j].Value = employee.CsvName;
                            worksheet.Cells["C" + j].Value = employee.CreatedOn;
                            worksheet.Cells["D" + j].Value = employee.StatusName;
                            worksheet.Cells["E" + j].Value = employee.UpdatedOn;
                        }
                        else
                        {
                            worksheet.Cells["A" + j].Value = employee.ToEmail;
                            worksheet.Cells["B" + j].Value = employee.Subject;
                            worksheet.Cells["C" + j].Value = employee.EmailType;
                            worksheet.Cells["D" + j].Value = employee.CreatedOn;
                            worksheet.Cells["E" + j].Value = employee.UpdatedOn;
                        }

                        j++;
                    }
                    worksheet.Cells.AutoFitColumns();
                    worksheet.Cells.Style.HorizontalAlignment = ExcelHorizontalAlignment.Left;
                    result = package.GetAsByteArray();
                }

                string fileName= "";

                switch (categoryId)
                {
                    case (int)MainCategory.Pending_Emails:
                        fileName = "Pending Emails.xlsx";
                        break;
                    case (int)MainCategory.Users:
                        fileName = "Pending Users.xlsx";
                        break;
                    case (int)MainCategory.Account:
                        fileName = "Pending Accounts.xlsx";
                        break;
                    case (int)MainCategory.Rms:
                        fileName = "Pending RMS.xlsx";
                        break;
                }

                return File(result, "application/octet-stream", fileName);
            }
            catch(Exception ex)
            {
                _logger.LogInformation(ex.Message + ex.StackTrace);
                return null;
            }
        } 
        #endregion
        #region Restart Windows Service
        public JsonResult ServiceOperations(string serviceName)
        {
            if(!ServiceExists(serviceName))
                return this.Json(new { success = true, message = "false" });
            
            string result;
            result = RestartService(serviceName, 10000);
            _logger.LogInformation(result);

Reports/Views/Admin/Index.cshtml
@{
    ViewData["Title"] = "Login";
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
    <script type="text/javascript" src="https://code.jquery.com/ui/1.11.1/jquery-ui.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.1/jquery.validate.min.js"></script>

    <link rel="stylesheet" href="https://code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width" />
    <title>Login</title>
    <style>
        .login-form {
            width: 300px;
            margin: 60px auto;
        }
        .login-form .title {
            margin-bottom: 30px;
        }
        .login-form .form-group {
            position: relative;
        }
        .login-form label.error {
            font-size: 12px;
            right: 0;
            position: absolute;
            color: red;
        }
        .login-form .button {
            margin-left: auto;
            margin-top: 30px;
            display: block;
        }
         .loader {
            position: fixed;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            border: 16px solid #f3f3f3;
            border-radius: 50%;
            border-top: 16px solid #3498db;
            width: 120px;
            height: 120px;
            -webkit-animation: spin 2s linear infinite; /* Safari */
            animation: spin 2s linear infinite;
            z-index:1000;
        }

        @@keyframes spin {
            0% {
                transform: rotate(0deg);
            }

            100% {
                transform: rotate(360deg);
            }
        }
    </style>
</head>
<body>
    <div class="loader" style="display:none;"></div>
    <div class="login-form">
        <h2 class="title">Login</h2>
        <form action="\Admin\Login" method="post" id="login">
            <div class="form-group">
                <label for="username">
                    <span class="required">Username</span>
                </label>
                <input id="username" name="username" class="text required input form-control" type="text">
            </div>
            <div class="form-group">
                <label for="password">
                    <span class="required">Password</span>
                </label>
                <input name="password" type="password" class="text required input form-control" id="password">
            </div>
            <div class="form-group">
                <label id="lblAuthentication" style="display:none">
                    <span class="required" style="color:red">Invalid Credentials</span>
                </label>
            </div>
            <div><input type="submit" class="button --blue btn btn-primary" value="Login"></div>
        </form>
    </div>
</body>
</html>

<script type="text/javascript">

    $("#login").validate({
        rules: {
            username: {
                required: true,
            },
            password: {
                required: true,
                minlength: 3
            },
        },
        messages: {
            "username": {
                required: "This field is required.",
            }
        },
        submitHandler: function (form) {
            $(".loader").show();
            $(".button").attr("disabled", true);

            var serializedForm = $('#login').serialize();
            $.ajax({
                url: '@Url.Action("Login", "Admin")',
                type: "POST",
                dataType: "json",
                data: serializedForm,
                success: function (result) {
                    $(".loader").hide();
                    $(".button").attr("disabled", false);
                    if (result == "true") {

                        location.href = '@Url.Action("Index", "Reports")';
                    }
                    else {
                        $('#lblAuthentication').show();
                    }
                },
                error: function(xhr, status, error) {}
            });
        }
    });
</script>